[package]
name = "unix_socket"
version = "0.2.3"
authors = ["Steven Fackler <sfackler@gmail.com>"]
license = "MIT"
description = "POSIX domain socket bindings"
repository = "https://github.com/sfackler/rust-unix-socket"
documentation = "https://sfackler.github.io/rust-unix-socket/doc/unix_socket"
readme = "README.md"
keywords = ["posix", "unix", "socket", "domain"]

[dependencies]
libc = "0.1"
debug-builders = "0.1"

[dev-dependencies]
temporary = "0.0.4"
